/*
 * Ethereum transactions manager
 *
 * Ethereum transactions manager
 *
 * API version: 1.0.0
 * Contact: alewkinr@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

// CreateTransactionRequest - New transaction request
type CreateTransactionRequest struct {
	To string `json:"to"`

	// The value to transfer in Wei (1000 Wei = 0,000000000000001 Ether)
	Value int64 `json:"value"`
}

// AssertCreateTransactionRequestRequired checks if the required fields are not zero-ed
func AssertCreateTransactionRequestRequired(obj CreateTransactionRequest) error {
	elements := map[string]interface{}{
		"to":    obj.To,
		"value": obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateTransactionRequestConstraints checks if the values respects the defined constraints
func AssertCreateTransactionRequestConstraints(obj CreateTransactionRequest) error {
	return nil
}
