/*
 * Ethereum transactions manager
 *
 * Ethereum transactions manager
 *
 * API version: 1.0.0
 * Contact: alewkinr@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

// ErrInternalError - Internal error response
type ErrInternalError struct {
	Message string `json:"message"`
}

// AssertErrInternalErrorRequired checks if the required fields are not zero-ed
func AssertErrInternalErrorRequired(obj ErrInternalError) error {
	elements := map[string]interface{}{
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertErrInternalErrorConstraints checks if the values respects the defined constraints
func AssertErrInternalErrorConstraints(obj ErrInternalError) error {
	return nil
}
