/*
 * Ethereum transactions manager
 *
 * Ethereum transactions manager
 *
 * API version: 1.0.0
 * Contact: alewkinr@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

// ErrBadRequest - Bad request error response
type ErrBadRequest struct {
	Message string `json:"message"`
}

// AssertErrBadRequestRequired checks if the required fields are not zero-ed
func AssertErrBadRequestRequired(obj ErrBadRequest) error {
	elements := map[string]interface{}{
		"message": obj.Message,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertErrBadRequestConstraints checks if the values respects the defined constraints
func AssertErrBadRequestConstraints(obj ErrBadRequest) error {
	return nil
}
